# Generated by Django 2.2.7 on 2019-12-03 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to=video.models.get_upload_path)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
