# Generated by Django 2.2.7 on 2019-12-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
    ]
